# -*- coding: utf-8 -*-
"""15-LUGATLAR/DICTIONARY bilan ishlash .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhBIOpIq1-a4FFeeaTNdrzz7uxvsxBCi
"""





# 15-dars LUGATLAR va elementlari bilan ishlash
# HOMEWORK
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
python_words = {
    'integer':'Butun son',
    'float': "O'nlik son",
    'boolean':"Mantiqiy qiymat",
    'for':"Biror amalni qayta-qayta bajarish tsikli",
    'if':'Shartlarni tekshirish operatori'}

for key, value in sorted(python_words.items()):
    print(f"{key.title()} - {value}")

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

avlatlar = {
    "o'zbekiston":'toshkent',
    'aqsh':'washington d.c.',
    'rossiya':'moskva',
    'tojikiston':'dushanbe',
    "qirg'iziston":'bishkek',
    'qozog\'iston':'nursulton',
    'malayziya':'kuala-lumpur',
    'singapur':'sungapur',
    'italiya':'rim'}

print('Dunyo davlatlari:')
for davlat in sorted(davlatlar):
    print(davlat.upper())

print('\nDavlatlarning poytaxtlari')
for poytaxt in sorted(davlatlar.values()):
    print(poytaxt.title())

country = input('Qaysi davlatning poytaxtini bilishni istaysiz?:').lower()
capital = davlatlar.get(country)
if capital==None:
    print('Kechirasiz, bizda bu haqida ma\'lumot yo\'q')
else:
    print(f"{country.upper()}ning poytaxti {capital.title()} shahri")

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

restaran={
    'osh':35000,
    'somsa':24000,
    'qaynatma':3100,
    'salatlar':12000,
    'chuchvara':2311,
    'manti':2000,
    'shashlik':8000,
    'uygur':10000,
    'baliq':31000,

       }

taomlar=[]
for n in range(0,3):
  taomlar.append(input(f'marhamat {n+1} chi taomni kiriting>>>'))
print(taomlar)

for taom in taomlar:
  if taom.lower() in restaran:
    print(f'{taom.title()} : {restaran[taom]}')
  else:
    print(f'Uzur mijoz {taom.title()} menyuda yoq:')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

