# -*- coding: utf-8 -*-
"""16- Dars NESTING/funksiya ichiga boshqasini jamlash.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_p50JFE_BnZAIYzPpazbohs9rv0hAQd1
"""

# 16-DARS NESTING-bir funksiya ichiga boshqasini joylash


# car0={
#     'nomi':'kia k8',
#     'narxi':13400,
#     'joylashuvi':'inchon',
#     'yili':2018,
#     'kilometri':14888,
#     'firmasi':'kia',
#       }


# car1={
#     'nomi':'jentra',
#     'narxi':12000,
#     'joylashuvi':'seoul',
#     'yili':2010,
#     'kilometri':14888,
#     'firmasi':'chevrolet',
#       }


# car2={
#     'nomi':'hyundai lux7',
#     'narxi':12000,
#     'joylashuvi':'yeosu',
#     'yili':2010,
#     'kilometri':14888,
#     'firmasi':'hyundai',
#       }


# # bu 3 talugatdan bita list yasab joylemiz

# cars=[car0,car1,car2]
# for car in cars:
#   print(f' {car['nomi'].upper()} narxi {car['narxi']}$,'
#         f'{car['joylashuvi'].title()} shahrida turibdi,yurgan yoli {car['kilometri']}km ,'
#         f'yili {car['yili']} :\n' )

# #istalgan mahsinani biror malumotini chiqarmoqchi bo`lsak
# print(cars[0]['nomi'])
# print(cars[2]['kilometri'])

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# juda kop royxatlarni fo bilan oson yaratish

# new_cars=[]
# for n in range(10):
#    car={
#     'nomi':'newcar',
#     'narxi':13400,
#     'rang':None,
#     'joylashuvi':None,
#     'yili':2018,
#     'kilometri':14888,
#     'firmasi':None,
#     'karobka':"avto",
#       }
#    new_cars.append(car)

# #ekranga chiqarish uchun taritib bilan
# for car in new_cars:
#   print(car)

##endi dastlabki 3tasiga mashina mamotlarini kiritamiz
# for car in new_cars[0:3]:
#   car['rang']='qizil'
#   car['nomi']='malibu'
#   car['firmasi']='chevrolet'
# for car in new_cars:
#   print(car)
#qolganlarini masalan 7 tasini malumotlarini ozgartramiz

# for car in new_cars[3:10]:
#   car['rang']='qora'
#   car['nomi']='sonata 5'
#   car['firmasi']='hyundai'
#   car['kilometri']=100000
#   car['karobka']='mehanika'
# # for car in new_cars:
# #   print(car)

# for car in new_cars:
#   if car['karobka']=='avto':
#        car['narxi']=18000
#   else:
#       car['narxi']=14000

# for car in new_cars:
#   print(car)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# lugat ichi list joylash

# dasturchilar={
#     'ali':['c++','python'],
#     'vali':['java','cshap'],
#     'hakim':['bootstrap','sql'],
#     'salim':['django','ai']
#      }

# for ism,tillar in dasturchilar.items():
#   print(f' \n{ism.title()} : quyidagi dasturlash tillarini biladi:')
#   for til in tillar:
#     print(til.upper(),end=' ,')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# LUGAT ICHIDA LUGAT JOYLASH

# hamkasblar={

#     'ali': {
#        'familya':'jorayev',
#        'yoshi':27,
#        'kasbi':'dasturchi',
#        'tillar': ['c++','python'],
#        },

#     'hasan': {
#        'familya':'alimov',
#        'yoshi':42,
#        'kasbi':'doktor',
#        'tillar': ['bialogiya','anatomiya'] ,
#        },

#     'jam': {
#        'familya':'ganiyev',
#        'yoshi':36,
#        'kasbi':'matematik',
#        'tillar': ['algebra','geometriya'] ,
#        },
#   }


# for ism,info in hamkasblar.items():
#       print(f'\n {ism.title()} {info['familya'].title()}'
#             f'\n Yoshi : {info['yoshi']} da'
#             f' \n Kasbi : { info['kasbi'].upper()}'
#             f'\n Quyidagilarni biladi:')

#       for til in info['tillar']:
#             print(  f' {til.upper()}')


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# HOME WORK :


# alijon={
#     'ifo':'alijon sharipov',
#     'yosh':46,
#     'kasbi':'insta blogger',
#     'manzili':'namangan',
#     'ijodlari':['huquq videosi','tabiatni asraylik','sabirli bol','oila muqaddas']
#      }


# ozodbek={
#     'ifo':'ozodbek nazarbekov',
#     'yosh':50,
#     'kasbi':'qo`shiqchi',
#     'manzili':'andijon',
#     'ijodlari':['vatanim qoshigi','o`zbekiston jonim','sevgilim qoshigi','jonu dilim vatanim']
#      }

# otabek={
#     'ifo':'otabek shamsiyev',
#     'yosh':19,
#     'kasbi':'shaxmatchi jahon chempioni',
#     'manzili':'farg`ona',
#     'ijodlari':['osiyo shaxmati kitobi','shaxmat organmiz video darsi','shaxmat sirlari kitobi','oilada shaxmat darsi']
#      }

# valijon={
#     'ifo':'valijon shamsiev',
#     'yosh':42,
#     'kasbi':'qiziqchi',
#     'manzili':'navoiy',
#     'ijodlari':['kulgi dasturi','qiziqchilik sanati','sanat siri','oilada kulgu']
#      }

# mshlar=[alijon,ozodbek,otabek,valijon]
# print(f'4  mashhur shaxslar ro`yxati)')
# for shaxs in mshlar:
#     print(
#           f'\n{shaxs['ifo'].title()},'
#           f'{shaxs['yosh']} yosh da,'
#           f'kasbi :{shaxs['kasbi'].upper()},'
#           f'manzili {shaxs['manzili'].upper()}da yashaydi.'
#         )


# for shaxs in mshlar:
#   print(f'\n{shaxs['ifo'].title()},'
#         f'Quyidagi ijodlari bilan mashhur:\n ')
#   for ijod in shaxs['ijodlari']:
#         print(f'{ijod.title()}')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

oilam ={}
sevimliklar=[]

for n in range(0,4):
  ism=input(f'{n+1} chi Yaqin insoningiz ismini kiriting>>')

  print(' Uning sevimli 3 ta kitoblari royxatini kiriting :')
  for s in range(0,3):

      sevimlik=input(f'  d{s+1} - sevimli kitobi kiriting')

# print('hellio')

#Davom ettirishim kerak

