# -*- coding: utf-8 -*-
"""17- dars WHILE tsikli .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14H3uBZUhMpjxgoXh5_Jgmnsucaliw4He
"""

# 17- dars WHILE TSIKLI bilan ishlash
ism=input('ismingiz nima?')
savol=f"salom {ism.title()}, yoshingiz nechida?"
yosh=input(savol)
yosh=int(yosh)
height=input("bo`yingiz necha metr?")
height=float(height)

# #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
while sikle
son=1
while son<=10:
print(son,end =' ')
son=son+1
print('dastur tugadi')

# # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
sonni kvatratini qaytaruvchi dastur,agar sonni kiritmasdan
print('Kiritilgan sonning kvadratini qaytaruvchi dastur :')
savol='istalgan son kiriting'
savol+= " dastur to`xtashi uchun 'exit' deb yozing) :"
qiymat= ' '
while qiymat != 'exit':
qiymat = input(savol)
if qiymat != "exit":
print(f' {qiymat} ni kvadrati {float(qiymat)**2} ga teng')
print('\n Dastur tugadi')

# # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
print('Kiritilgan sonning kvadratini qaytaruvchi dastur :')
savol='istalgan son'
savol+='kiriting agar dasturni to`xtatish uchun "exit" deb yozing '
qiymat=" "
belgi=True
while belgi:
qiymat =input(savol)
if qiymat=='exit':
belgi=False
else:
print(float(qiymat)**2)
print('Dastur yakunlandi')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# BREAK -bu sindirish toxtatish degan manoni anglatadi dasturni istalgan vaqtda toxtatib qoyish uchun ishlatiladi.
sonlar =list(range(1,11))
for son in sonlar:
if son==7:
break
else:
print(f'{son} ni kvadrati {son**2}ga teng')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
continue - bu agar shart bajarilmasa dasturni boshiga qaytarib beradi boshidn boshlaydi
sonlar =list(range(1,11))
for son in sonlar:
if son==7:
continue
else:
print(f'{son} ni kvadrati {son**2}ga teng')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
son=0
while son<10:
son+=1
if son%2==0:
continue
else:
print(son)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
son=0
while son<=0:
 son+=1
 break
print(f'{son} ni kvadrati {son**2} ga teng')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# HOMWORK
print('\nYaxshi ko`rgan kitoblaringiz ro`yxatini aniqlaydigan dastur :')
kitob=" "
kitoblar=[]
savol ='Iltimos yaxshi korgan kitob nomini kiriting'
savol+='\n dasturni toxtatmoqchi bolsangiz "stop" deb yozing '
while kitob !="stop":
  kitob=input(savol)
  print(kitoba )

print('Dastur yakunlandi')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Muzeyga chipta narhi foydalanuvchining
# yoshiga bog'liq:
# 7 dan yoshlarga - 2000 so'm,
# 7-18 gacha 3000 so'm,
# 18-65 gacha 10000 so'm,
# 65 dan kattalarga bepul.
# Shunday while tsikl yozingki,
# dastur foydalanuvchi yoshini so'rasin
# va chipta narhini chiqarsin.
#Foydalanuvchi exit yoki quit deb yozganda
#dastur to'xtasin (ikkita shartni ham tekshiring).


yosh=' '
print("FOYDALANUVCHI YOSHIGA QARAB BILET NARXI DASTURI:\n")
savol='Chipta narxini bilish uchun yoshingizni kiriting ?'
while yosh!='exit':
    yosh=input(savol)
    if yosh=='exit' or yosh=='quit':
      break
    yosh=int(yosh)
    if yosh<7:
         print('Bilet narxi 2000 sum')
    if yosh>7 and yosh<=18:
         print('Bilet narxi 3000 sum')
    if yosh>18 and yosh<=65:
         print('Bilet narxi 10000 sum')
    if yosh>65:
         print('Bilet narxi 0 sum')
print('Dastur yakunlandi')


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

savol ="<<Kiritilgan sonning ildizini qaytaruvchi dastur >>.\n"
savol += "Musbat son kiriting "
savol += "(dasturni to'xtatish uchun 'exit' deb yozing): "
qiymat=' '
while True:
    qiymat = input(f'{savol}\n')
    if qiymat=='exit':
       break
    son=qiymat
    if float(son)<0:
        continue# agar foydalanuvchi manfiy kiritsa takrorlaymiz
    else:
        ildiz = float(son)**(0.5)
        print(f"{son} ning ildizi {ildiz} ga teng\n")
print('dastur yakunlandi')