# -*- coding: utf-8 -*-
"""19-dars functions /funksiyalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXjiHWEbyB_EG5IV505AW0bJQVZ4HUKR
"""

# 19-dars funksiyalar bilan ishlash



def yosh_hisobla(tugilgan_yil, joriy_yil=2020):
    """Foydalanuvchi tug'ilgan yilidan uning yoshini hisoblaydi"""
    print(f"Siz {joriy_yil-tugilgan_yil} yoshdasiz")

tugilgan_yil = int(input("Tug'ilgan yilingizni kiriting: "))

yosh_hisobla(tugilgan_yil)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def yosh_hisobla(tugilgan_yil, joriy_yil):
    """Foydalanuvchi tug'ilgan yilidan uning yoshini hisoblaydi"""
    print(f"Siz {joriy_yil-tugilgan_yil} yoshdasiz")

yosh_hisobla(joriy_yil=2025,tugilgan_yil=1993)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def salom_ber(ism):
    """Salom beruvchi funksiya"""

    print(f"Assalomu alaykum! {ism.title()}")

salom_ber('hasan')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def toliq_ism(ism, familiya):
    """Foydalanuvchi ism va familiyasini jamlab chiqaruvchi funksiya"""

    print(f"Foydalanuvchi ismi: {ism.title()}\n"
          f"Foydalanuvchi familiyasi: {familiya.title()}")

toliq_ism('olim','hakimov')

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# UYGA VAZIFA

def tyil_hisobla(ism,yosh):
    'TUGILGAN YIL HISOBLAYDIGAN FUNKSIYA '
    print(f" {ism} ning tug`ilgan yili {2026-yosh} ")

tyil_hisobla('ali',27)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def son_darajahisob(son):
    "SONNING KUBI VA KVADRATINI CHIQARADIGAN FUNKSIYA"
    print(f"{son} ning kvadrati= {son**2}\n"
           f"{ son} ning kubi = {son**3}")

son_darajahisob(3)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def jufttoq_hisobla(son):
    "SONNNING JUFT YOKI TOQLIGINI HISOBLAB BERUVCHI FUNKSIYA"
    if son%2==0:
        print(f" {son} soni juft son")
    else:
        print(f" {son} soni toq  son ")

jufttoq_hisobla(57)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def kattasini_aniqlovchi(son1,son2):
    "SONNNI KATTASI YOKI TENGLIGINI ANIQLOVCHI FUNKSIYA"
    if son1-son2<0:
      print(f" {son2} eng kattasi")
    if son1-son2>0:
      print(f" {son1} eng kattasi")
    if son1==son2:
      print(f" Bu sonlar o`zaro teng ")

kattasini_aniqlovchi(46,23)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def daraja_hisoblovchi(son,daraja=2):
    "SONNING DARAJASINI HISOBLOVCHI DASTUR"
    print( f" {son} ning {daraja} darajasi {son**daraja}")

daraja_hisoblovchi(3,5)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def qoldiq_tekshir(son):
  """sonni intervalda qoldiqsiz bolinishini
  tekshiradigan funksiya"""
  for n in range(2,11):
     if son%n==0:
        print(f" {son} soni {n} ga qoldiqsiz bo`linadi")


qoldiq_tekshir(55)
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

