# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhBIOpIq1-a4FFeeaTNdrzz7uxvsxBCi
"""

2-dars
print('Assalom alaykum')
print(Hayrli tong!)
print(2+4*2)
print(19/5)
print(2**4)