# -*- coding: utf-8 -*-
"""20_dars FUNCTIONS /funksiyalar bilan ishlash7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1f4eYLlUTk9bTrYtzJPX1WAKwlEnTbU
"""

# 20-dars FUNKSIYALAR BILAN ISHLASH
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
def tism_yasa(ism,familya,otasining_ismi=''):
  "toliq ism yasab beradigan funksiya"
  if otasining_ismi:
    tism=f"{ism} {otasining_ismi} {familya}"
  else:
    tism=f"{ism} {familya}"
  return tism.title()

talaba1 = tism_yasa('olim','aliyev','bekzadovich')
talaba2 = tism_yasa('gani','boriev')
print(f"Darsga kelmagan talabalar {talaba1} va {talaba2}")

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def avto_info(kompaniya,model,rangi,korobka,yili,narx=None):
    """Mashina haqida malumotlarni
    dictionaryga jamlovchi funksiya"""
    avto={
        'kompaniya':kompaniya,
        'model':model,
        'rangi':rangi,
        'korobka':korobka,
        'yili':yili,
        'narx':narx }
    return avto

avto1= avto_info('gm','malibu','qora','avtomat',2019)
avto2= avto_info('gm','gentra','oq','mehanika',2020,350000)

avtolar=[avto1,avto2]
print('onlayn bozordagi mavjud mahinalar:')

for avto in avtolar:
   if avto['narx'] :
      narx=avto['narx']
   else:
      narx="noma'lum"
   print(f"{avto['rangi']} {avto['model']} . Narxi:{narx}")

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# funksiyadan royxat qaytaramiz

def oraliq_yara(min,max,qadam=1):
  "oraliq yaratuvchi funksiya "
  oraliq=[]
  while min<=max:
     oraliq.append(min)
     min+=qadam

  return oraliq

oraliq_yara(5,27,3)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# funksiyalarni takrorlash uchun tsikldan foydalanishimi mumkin

def avto_info(kompaniya,model,rangi,korobka,yili,narx=None):
    """Mashina haqida malumotlarni
    dictionaryga jamlovchi funksiya"""
    avto={
        'kompaniya':kompaniya,
        'model':model,
        'rangi':rangi,
        'korobka':korobka,
        'yili':yili,
        'narx':narx }
    return avto
# >>>>>>>>>>>>>>>>>>>>>>

print("saytimizdagi avtolar royxatini shakllantiramiz:")
avtolar=[] #salondagi avtolar uchun bo`sh royxat

while True:
  print(f"\nQuyidagi malumotlarni kiriting",end=' ')
  kompaniya=input(" Ishlab chiqaruvchi : ")
  model=input("modeli: ")
  rangi=input("rangi:")
  korobka=input("korobka:")
  yili=input("ishlab chiqarilgan yili:")
  narhi=input('narxi:')


  #Foydalanuvchi kiritdan ma'lumotlardan avto_info yordamida
  #lug'at shakllantirib, har bir lug'atni ro'yxatga qo'shamiz:

  avtolar.append(avto_info(kompaniya, model, rangi, korobka, yili, narhi))


  #yangi avto qo`shish qo`shmaslikni so`remiz
  javob =input("yangi avto qo`shamizmi (ha/yoq):")
  if javob=="yoq":
    break

print('Salonimizdagi avtolar:')
for avto in avtolar:
   if avto['narx'] :
      narx=avto['narx']
   else:
      narx="noma'lum"
   print(f"{avto['rangi']} {avto['model']} . Narxi:{narx}")




# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
UYGA VAZIFA


def foydalanuvchi(ism,familya,tyili,tjoyi,email,telefon=None):
   "FOYDALANUVCHI MALUMOTLARINI OLADIGAN FUNKSIYA"
   info={
     'ism':ism,
     'familya':familya,
     'tyili':tyili,
     'tjoyi':tjoyi,
     'email':email,
     'telefon':telefon
      }
   return info


malumotlar=[]
while True:
  ism=input('Foydalanuvchi nomini kiriting :')
  familya=input('Familya kiriting :')
  tyili=input('Tugilgan yilini kiriting :')
  tjoyi=input('Tug`ilgan joyini kiriting :')
  email=input('emailni kiriting :')
  telefon=input('(ixtiyoriy) Telefon raqam kiriting :')

  malumotlar.append(foydalanuvchi(ism,familya,tyili,tjoyi,email,telefon))

  javob=input('boshqa talaba malumot qoshasizmi (ha/yoq)?')

  if javob=="yoq":
    break

for info in malumotlar:
   print(f" \n{info['ism'].title() }{info['familya'].title()}"
         f" email: {info['email']} \n"
        f" telefon raqami:{info['telefon']}")


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def sonlar_kattasi(x,y,z):
   "Sonlarnikattasini chiqaradigan funksiya"
   max=x
   if y>=max:
      max=y
   if z>=max:
      max=z
   return max

sonlar_kattasi(3,15,7)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def info_aylana(radius):
   " aylana malumotlarini chiqaradigan funksiya"
   PI=3.14
   info={
   "radius":radius,
   "peremetri":2*PI*radius,
   "diametri":2*radius,
   "yuzi":PI*radius**2}
   return info

info_aylana(6)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def tub_sonlar(son1=1,son2=231234567890123):
  "oraliqdagi tub sonlar chiqaruvchi funksiya"

  tubsonlar=[]
  for n in range(son1,son2+1):
    tub=True

    if n==1:
      tub=False
    elif  n==2:
      tub=True
    else:
      for x in range(2,n):
        if n%x==0:
          tub=False
    if tub:
      tubsonlar.append(n)
  return tubsonlar

print(tub_sonlar(8,5675675787))

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def fibonacci(n):
    sonlar = []
    for x in range(n):
        if x == 0 or x == 1:
            sonlar.append(1)
        else:
            sonlar.append(sonlar[x - 1] + sonlar[x - 2])
    return sonlar


print(fibonacci(10))

