# -*- coding: utf-8 -*-
"""21-dars functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zy5_WRyTP_LI3unJVnTw7u3e4dlXIyFq
"""

# 21- darsda funksiylar bilan ishlshni davom ettiramiz

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
def bahola(ismlar):
  baholar={}
  while ismlar:
    ism=ismlar.pop()
    baho=input(f'Talaba {ism.title()} ning bahosini kiriting:')
    baholar[ism]=baho
  return baholar

talabalar=['ali','vali','hasan','husan']

baholar=bahola(talabalar)
print(baholar)


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# Home work

def royxat_ber(royxat):
  "ROYXATNI KATTA XARF BILAN QAYTARUVCHI"


  for n in range(len(royxat)):
    royxat=royxat[:]
    royxat[n]=royxat[n].title()
  return royxat

news=['ali','gani','salim','gulom','amir','bakir']
yangi_ismlar = royxat_ber(news)

print(yangi_ismlar)
print(news)


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
def katta_harf(matnlar):
    matnlar = matnlar[:]
    for i in range(len(matnlar)):
        matnlar[i]=matnlar[i].title()
    return matnlar

ismlar = ['ali', 'vali', 'hasan', 'husan']
yangi_ismlar = katta_harf(ismlar)
print(ismlar)
print(yangi_ismlar)
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

"""To install a Python library, you can use the `pip install` command in a code cell. For example, to install the `pandas` library, you would run:"""

!pip install pandas

"""After installation, you can import and use the library in your code."""

