# -*- coding: utf-8 -*-
"""22-dars *ARGS/**KWARGS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0pombzzGQpFi-3_O2aYxwYKyz5HqaZS
"""

# 22-DARS MOSLASHUVCHAN FUNKSIYA


# Agar funksiyangiz bir nechta argument qabul qilishi
# kerak bo'lsa-yu, lekin siz argumentlar sonini
# aniq bilmasangiz, Pythonda istalgancha qiymat
# qabul qiluvchi funksiya yaratish imkoniyati bor.

def suma(*sonlar):
  "kiritilgan sonlar yig`indisini hisoblaydigan funksiya"
  yigindi=0
  for son in sonlar:
    yigindi+=son
  return yigindi

suma(12,12,12,121,21,21,21,21,21,12,2,121,2)
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def summa(*sonlari):
    """Kiritilgan sonlar yig'indisini hisoblaydigan funksiya"""
    return sum(sonlari)

summa(112,233,132)
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def summa(x,y,*sonlar):
  "yigindi hisoblaydigan funksiya"
  return x+y+__builtins__.sum(sonlar)

summa(3,4,5,6,7,89,0)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def avto_info(kompaniya,model,**malumotlar):
  "avto malumotlarni lugat ko`rinishida qaytaruvchi funksiya"
  malumotlar['kompaniya']=kompaniya
  malumotlar['model'] =model
  return malumotlar

avto1=avto_info('GM','malibu',rang='qizil',yil=2029)
avto2=avto_info('kia','malibu',rang='qora',narx=35000)

print(avto1)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# uyga vazifa

def kopaytma(*sonlar):
  "sonlarni kopaytmasini qaytaruvchi funksiya"
  kopaytma=1
  for son in sonlar:
    kopaytma=kopaytma*son
  return kopaytma

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def talaba_info(ism,familya,**malumotlar):
  """talaba malumotlarini lugat korinishida
  qaytaruvchi funksiya"""

  malumotlar['ism']=ism
  malumotlar['familya']=familya
  return malumotlar

talaba1=talaba_info('ikromjon','tojiboyev',yili='1999',yoshi='26')
print(talaba1)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

