# -*- coding: utf-8 -*-
"""24-dars LAMBD funksiyasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKPKV18nJlZ-L2IAAD1GQkWSnDxjHUlQ
"""

# 24-dars lambd funksiyasi nomsiz funksiya hisoblanadi


lambda argument1,argument2:ifoda #bunda istalgancha argument kiritib ifoda soddagina boladi
uzunlik=lambda pi,r:2*pi*r
from math import pi
r=int(input('radiusni kiriting'))
print(uzunlik(pi,r))

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
x ni y chi darajasini hisoblaydigan funksiya
kvadrat=lambda x,y:x**y
print(kvadrat(4,17))

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

def daraja(n):
  return lambda x:x**n

kav=daraja(2)
print(kav(6))

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>/
map funksiyasi bu boshqa bir funksiya va argumentni qaul qiladi

from math import sqrt

sonlar=list(range(1,11))
ildizlar=list(map(sqrt,sonlar))#bu yerda listdagi har biriga ildiz hisobladi
# print(ildizlar)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>..
sonlar=list(range(1,25))
def daraja2(x):
  "sonni kvadratini hisoblaydigan funksiya"
  return x*x
kvadratlar=list(map(daraja2,sonlar))
print(kvadratlar)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

a=[3,5,7]
b=[6,7,8]
a_plus_b=list(map(lambda x,y:x+y,a,b))
print(a_plus_b)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# sample() bu malum bir royxatdan istalgan cha tasodfiy sonlarni tanlab beradi
# filter() funksiyasi bu ha map kabi yonaltrib beradi

import random as r

sonlar= list(r.sample(range(100),10))
print(sonlar)

def juftmi(x):
  "juftmi tekshiradigan funksiya "
  return x%2==0

juft_sonlar=list(filter(juftmi,sonlar))
print(juft_sonlar)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# b harfini topib beruvchi dastur
mevalar=['olma','anor','behi','gilos','anjir','uzum','anjir','banan']
harf='b'
mevalar_b=list(filter(lambda meva: meva.startswith(harf),mevalar))
print(mevalar_b)


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
5ta harfda kichik sozlarni topib beradi
mevalar2 = list(filter(lambda meva:len(meva)<=5, mevalar))
print(mevalar2)

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# boshi a va oxir r bilan bolgan sonlarni chiqarib beradi
mevalar3=list(filter(lambda meva:(meva.startswith('a') and meva.endswith('r')), mevalar))
print(mevalar3)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

