# -*- coding: utf-8 -*-
"""25-dars SON TOPISH OYINI /FIND NUMBER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp5_nkG3dY8CbRSuIV7Ja4otNqPSnxjr
"""

# 25-dars SOZ TOPISH OYINI


while True:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  n=int(input(" Nechigacha oraliqda sonni topish o'yinini o`ynaymiz max son  kiriting !!"))
  sonlar=list(range(n))

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#  1-qism
  import random as rd
  son = rd.choice(sonlar)
  takror=0
  while True:
    takror+=1
    raqam=int(input(f"\n {n} gacha sonlardan birorta o`ylagan son kiriting>>"))
    if raqam<son:
      print(f"men o`ylagan son {raqam} dan kattaroq ")
    if raqam>son:
      print(f"men o`ylagan son {raqam} dan kichikroq")

    if raqam==son:
      print(f"Tabriklayman ! men o`ylagan son {raqam} ")
      break
  print(f"\nSiz {takror} urunishda men o`ylagan sonni topdingiz !")

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# 2-qism
  raqam2=input(f"Endi siz {n} gacha biror son o`ylab kiriting men topaman>>")
  takror2=0
  while True:
    son2 = rd.choice(sonlar)
    takror2+=1
    javob2=input(f"siz {son2} ni o'yladingizmi (ha/yoq)")
    if javob2=='ha':
      print(f"\nMen siz oylagan sonni {takror2} martada topdim")
      break

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# 3-qism
  if takror2>takror:
    print(f' \nTABRIKLAYMAN! SIZNING O`YINDA{takror2} IMKONDA TOPIB YUTDINGIZ')
  elif takror2<takror:
    print(f' \nMEN O`YINDA {takror} IMKONDA TOPIB  YUTDIM')
  else:
    print(f' \nBIZ O`YINDA {takror} IMKONDA TOPIB  DURANG O`YNADIK')
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  javob3=input(f"\nYANA O`YIN O`YANYMIZMI (HA/YOQ)?")
  if javob3=='yoq':
    break

"""1.komputer malum oraliq son oyledi va shuni ichida ixtiyoriy bitasini random tanladi ,tanlagan soni odam kiritgan son bilan teng bo`lguncha aylantradi,teng bo`lsa topdingiz urinishlar sonini aytadi.

2-qism.men son oyleman komputer taxmin qilib topish harakat qiladi.agar topsa necha marta urunishda topganimni chiqarib beradi.
"""