# -*- coding: utf-8 -*-
"""28-dars CLASS /KLASLAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CN-q88q1rYGlLmIFFNzhLuJkHs64BwnN
"""

# 28- DARS CLASS

x=10
print(type(x))
matn='salom'
print(type(matn))

>>>>>>>>>>>>>>>>>>>>>>>

class Talaba:
    def __init__(self,ism,familya,tyil):
      self.ism=ism
      self.familya=familya
      self.tyil=tyil

    def get_name(self):
      return self.ism

    def get_age(self,yil=2026):
      return yil-self.tyil

    def get_lastname(self):
      return self.familya

    def tanishtr(self):
      return f"Ismim {self.ism} familyam {self.familya} ,{self.tyil} tug`ilganman"

talaba1=Talaba('olim','olimov',2000)
talaba2=Talaba('hasan','husanov',2004)
talaba3=Talaba('alihon','bakirov',2003)

talaba2.tanishtr()
talaba3.get_lastname()


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# HOME WORK
class user:
  def __init__(self,name,lastname,email,etc):
    self.name=name
    self.lastname=lastname
    self.email=email
    self.etc=etc

  def get_name(self):
      return self.name

  def get_info(self):
      return f"Mening ismim {self.name} familyam {self.lastname} ,email manzilim {self.email} va telfon raqamim {self.etc} "

user1 =user('Karim','Tursunov','ikromjon1205@gmail.com',1044724)
user2 =user('Jasur','Aliyev','sakjdahdj@gmail.com',109865625)

user1.get_info()
user2.get_name()

