# -*- coding: utf-8 -*-
"""29-OOP .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3YRAjmB59kcI6YeoCugqyRWpFf-zPvX
"""

# 29-dars OOP BILAN ISHLASH

class Talaba:
  """"Talaba nomli klass """
  def __init__(self,ism,familya,tyil):
    """Talabaning xusussiyatlari"""
    self.ism=ism
    self.familya=familya
    self.tyil=tyil
    self.familya
    self.bosqich=1

  def get_fullname(self):
    "ismini qaytaradi"
    return self.ism.title() +f' '+ self.familya.title()

  def set_bosqich(self,yangi_bosqich):
    "talabaning bosqichini yangilovchi metod"
    self.bosqich=yangi_bosqich

  def update_bosqich(self):
    "Talabaning bosqichini 1 taga ko`paytirish"
    self.bosqich+=1


talaba1=Talaba('Hasan','Tojiyev',1999)
talaba2=Talaba('Juma','hakimov',2009)

# # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

class Fan():
  "Fan nomli klass"
  def __init__(self,nomi):
    self.nomi=nomi
    self.talabalar_soni=0
    self.talabalar=[]

  def add_student(self,talaba):
     "fanga talabalarni qoshish"
     self.talabalar.append(talaba)
     self.talabalar_soni+=1

  def get_students(self):
    "Fanga yozilgan talbaalar haqida malumot"
    return [talaba.get_fullname() for talaba in self.talabalar]



  def see_methods(klass):
    return [method for method in dir(klass) if method.startswith('__') is False]


matem=Fan('Oliy matematika')
matem.talabalar_soni
talaba1.ism
matem.add_student(talaba1)
matem.talabalar_soni
matem.add_student(talaba2)
matem.talabalar_soni
matem.talabalar
matem.get_students()
dir(Talaba)
talaba1.__dict__.values()
matem.see_methods()

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.
# HOME WORK

class Avto:
  "avtomobil klasi"
  def __init__(self,model,rang,korobka,narx,yili):
    self.model=model
    self.rang=rang
    self.korobka=korobka
    self.narx=narx
    self.yili=yili
    self.kilometr=0

  def get_info(self):
    "malumotlarni qaytaradigan"
    return f" Mashina nomi {self.model} rangi {self.rang} karobkasi {self.korobka} yili {self.yili} va yurgan yoli {self.kilometr}"

  def update_km(self):
    "yurgan km yangilaydi"
    new_klometr = int(input("yurgan yolini kiriting"))
    self.klometr=new_klometr
    return self.kilometr

  def get_km(self):
    "kilometr korsatdi"
    return self.kilometr

avto1=Avto('NEXIA','QORA','avtomat',25600,2013)
avto2=Avto('Ninja','OQ','mehanika',23440,2023)

# avto1.get_info()
# avto1.update_km()
# avto1.get_km()


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>//

class Avtosalon:
  "avtosalon hussusyatlari"
  def __init__(self,nomi,manzil,tel):
    "salon hussusyatlari"
    self.nomi=nomi
    self.manzil=manzil
    self.tel=tel
    self.sotuv_avtolar=[]

  def add_avto(self,avto_new):
    "yangi avto qoshish"
    self.sotuv_avtolar.append(avto_new)

  def salon_info(self):
    "salon haqida malumot chiqaradi"
    return f"Avtosalon nomi {self.nomi} manzili {self.manzil} telefon raqami {self.tel}"

  def get_avtolar(self):
    "salondagi avtolar chiqaradi "
    return [x.get_info() for x in self.sotuv_avtolar]

Buxoro_avto=Avtosalon('Nayza avtosalon','Buxoro',786654454)
Buxoro_avto.add_avto(avto1)
Buxoro_avto.add_avto(avto2)
Buxoro_avto.get_avtolar()

